version: '3.7'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      # - 3000:3000
      - 9229:9229
      - 8181:8181
    command: npm start